defaults:
  - _self_

version: 'HotDog Classifier v1'

hydra:
  run:
    dir: ./outputs/${params.model}/${now:%Y-%m-%d}/${now:%H-%M-%S}

################# Experiment Settings #################
device: 'cpu'
debug: False
experiment_name: "TEST"
n_devices: 1

################# W&B Settings #################
wandb:
  use_wandb: True
  project: "HotDog Classifier"
  group: ${params.model}


################# Metrics Settings #################
metrics: ['acc','loss','f1','precision','recall']
track_metric: 'loss'
log_every_n: 1


################# Hyperparameters #################
params:
  # define model
  model: 'BASIC_CNN'
  n_classes: 10
  verbose: True

  # param related to dataloader and data
  workers: 1
  augment: True 
  # etc

  # model related params
  optimizer: 'Adam'
  lr: 0.01
  bs: 64
  weight_decay: 0
  epochs: 10
