defaults:
  - _self_

version: 'HotDog Classifier v1'

hydra:
  run:
    dir: ./outputs/${params.model}/${now:%Y-%m-%d}/${now:%H-%M-%S}

################# Experiment Settings #################
device: 'cuda'
debug: False
experiment_name: "efficientnet_increased_image_size"
n_devices: 1

################# W&B Settings #################
wandb:
  use_wandb: True
  project: "HotDog Classifier"
  group: ${params.model}


################# Metrics Settings #################
metrics: ['acc','loss','f1','precision','recall']
track_metric: 'loss'
log_every_n: 1


################# Hyperparameters #################
params:
  # define model
  model: 'efficientnet'
  n_classes: 2
  verbose: True

  # param related to dataloader and data
  workers: 1
  augment: False
  image_size: 256
  normalize: True

  # model related params
  optimizer: 'Adam'
  lr: 0.01 # 0.0001 BASIC_CNN
  bs: 64
  weight_decay: 0
  epochs: 1
  early_stopping: False

  enable_dropout: True
  dropout_rate: 0.25

  # ONLY applciable for effcientnet
  pretrained: True
  freeze_params: 0.9 # [0,1], 1 => freeze all weights except head
