name: 'efficientnet'
training:
  lr: 0.0001
  weight_decay: 0
  enable_dropout: True
  dropout_rate: 0.25
  optimizer: 'Adam'
  epochs: 70
  early_stopping: False
  pretrained: True
  freeze_params: 0.9 # [0,1]
